# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  run-test-app:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub. 
    docker:
      - image: cimg/python:3.12.0
    # Add steps to the job
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: pip install numpy pytest
      - run:
          name: Run Sparse Matrix
          command: python sparse_recommender.py
      - run:
          name: Run Test Cases 
          command: pytest test_sparse_recommender.py

  build-and-push:
        docker:
            - image: cimg/python:3.8
        steps:
            - checkout
            - setup_remote_docker:
                version: 19.03.13
            - run:
                name: Docker build
                command: docker build -t $DOCKERHUB_USERNAME/circleci_sparse_matrix:${CIRCLE_SHA1} .
            - run:
                name: Authenticate with Docker Hub
                command: echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
            - run:
                name: Push Docker Image to Docker Hub
                command: docker push $DOCKERHUB_USERNAME/circleci_sparse_matrix:${CIRCLE_SHA1}

# Orchestrate jobs using workflows
workflows:
  version: 2
  sparse-recommender:
    jobs:
      - run-test-app
          filters:
            branches:
              only: main
      - build-and-push
          requires:
            - run-test-app
          filters:
            branches:
              only: main

